{% set name = "decaylanguage" %}
{% set version = "0.15.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decaylanguage-{{ version }}.tar.gz
  sha256: 68a249d50f2cd51f89130281c7ecc6b987e03a1db8c2ec767362bf9de92d8d97

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - hatchling
    - hatch-vcs
  run:
    - attrs >=19.2
    - deprecated
    - python-graphviz
    - lark >=1.0.0
    - numpy >=1.12
    - pandas >=0.22
    - particle ==0.21.*
    - plumbum >=1.6.9
    - importlib_resources >=2.0
    - python >=3.6

test:
  imports:
    - decaylanguage
    - decaylanguage.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/decaylanguage
  summary: A language to describe particle decays, and tools to work with them.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
