{% set name = "decaylanguage" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decaylanguage-{{ version }}.tar.gz
  sha256: d03c28b27be723e3c171d7fc07a94c18c87573613a16b2b42fb63dceb451cd37

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - hatchling
    - hatch-vcs
  run:
    - attrs >=19.2
    - deprecated
    - python-graphviz
    - lark-parser >=0.11.0
    - numpy >=1.12
    - pandas >=0.22
    - particle ==0.20.*
    - plumbum >=1.6.9
    - importlib_resources >=2.0
    - python >=3.6

test:
  imports:
    - decaylanguage
    - decaylanguage.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/decaylanguage
  summary: A language to describe particle decays, and tools to work with them.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
