{% set name = "decaylanguage" %}
{% set version = "0.14.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/DecayLanguage-{{ version }}.tar.gz
  sha256: 0979002a2bc548bc4bb1e3fb598069aa010ffa1f26441f710dd8ff0c9f98dfa4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - attrs >=19.2
    - deprecated
    - python-graphviz
    - lark-parser >=0.11.0
    - numpy >=1.12
    - pandas >=0.22
    - particle ==0.20.*
    - plumbum >=1.6.9
    - importlib_resources >=2.0
    - python >=3.6

test:
  imports:
    - decaylanguage
    - decaylanguage.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/decaylanguage
  summary: A language to describe particle decays, and tools to work with them.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
