{% set name = "decaylanguage" %}
{% set version = "0.18.5" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/decaylanguage-{{ version }}.tar.gz
  sha256: 1e955efa0c5e76e222a92723856d94f5db7197ab28262036b895010007f739a2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - attrs >=19.2
    - deprecated
    - python-graphviz
    - lark >=1.0.0
    - numpy >=1.12
    - pandas >=0.22
    - particle >=0.22.0
    - plumbum >=1.7.0
    - importlib_resources >=2.0
    - python >={{ python_min }}

test:
  imports:
    - decaylanguage
    - decaylanguage.data
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scikit-hep/decaylanguage
  summary: A language to describe particle decays, and tools to work with them.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scikit-hep/decaylanguage
  doc_url: https://decaylanguage.readthedocs.io/

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
    - conda-forge/scikit-hep
