{% set name = "decaylanguage" %}
{% set version = "0.10.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/DecayLanguage-{{ version }}.tar.gz
  sha256: 4aa3f5dd1a3046286a16202c2253011a0437b3602618049de30f1b9b7411480e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs >=19.2
    # Only required for [py<37] but always include so this can be noarch: python
    - importlib_resources >=1.0
    - lark-parser >=0.8.0,<0.8.6
    - numpy >=1.12
    - pandas >=0.22
    - particle ==0.14.*
    - plumbum >=1.6.9
    - pydot
    - python >=3.6
    - six >=1.11

test:
  imports:
    - decaylanguage
    - decaylanguage.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/decaylanguage
  summary: A language to describe particle decays, and tools to work with them.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
    - eduardo-rodrigues
