schema_version: 1

context:
  name: decaylanguage
  version: "0.20.1"
  python_min: '3.9'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/decaylanguage-${{ version }}.tar.gz
  sha256: c6d887f50b04596e2fce40337153f7f2e0a730c9311a01ab090992f5083c889d

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - attrs >=19.2
    - python-graphviz
    - lark >=1.0.0
    - numpy >=1.19.3
    - pandas >=1
    - particle >=0.26.0
    - hepunits >=2.4.0
    - plumbum >=1.7.0

    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - decaylanguage
        - decaylanguage.data
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: A language to describe particle decays, and tools to work with them.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/decaylanguage
  repository: https://github.com/scikit-hep/decaylanguage
  documentation: https://decaylanguage.readthedocs.io/

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
    - conda-forge/scikit-hep
